title: Local Annotation Server
description: "Local annotation server that allows for easy annotation creation."
baseurl: "/annotate"
url: "https://dnoneill.github.io"

markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag

exclude: [Rakefile, Gemfile*, vendor]
include: [feed.xml]

theme: annotate-theme
remote_theme: dnoneill/annotate-theme

collections:
  annotations:
    output: true
    permalink: /annotations/:name
  ranges:
    output: true
    permalink: /ranges/:name
  helpdocs:
    output: true
    permalink: /help/:name
  annotation_data:
    output: true
    permalink: /annotations/:name
  iiifproviders:
    permalink: /:path
  custom_images:
    metadata:
      source: 'objects.csv' # path to the metadata file, must be within '_data'
    images:
      source: 'custom' # path to the directory of source images, must be within '_data'

webrick:
  headers:
    "Access-Control-Allow-Origin": "*"

api_server: https://limitless-plains-74009.herokuapp.com/
endpoint: https://limitless-plains-74009.herokuapp.com/write_annotation/

exclude:
  - ENV/
  - imported_roles

lunr_settings:
  collections: [annotation_data]
  atozsortfield: slug
  displayfields:
    - {field: slug, headerfield: true, highlight: false}
    - {field: imagescr, headerimage: true, highlight: false}
  fields:
  - boost: 10
    jekyllfields: [content]
    searchfield: content
  - boost: 10
    jekyllfields: [tags]
    searchfield: tags
    facetfield: true

  fuzzysearchfields: [content]
